# Generated by Django 6.0.1 on 2026-01-29 06:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutopsyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=20, unique=True)),
                ('case_type', models.CharField(choices=[('NORMAL', 'Clinical/Hospital'), ('FORENSIC', 'Forensic/Crime Division')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Arrival'), ('IN_PROGRESS', 'Examination In Progress'), ('TOX_PENDING', 'Pending Toxicology'), ('COMPLETE', 'Case Closed')], default='PENDING', max_length=20)),
                ('deceased_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('ob_number', models.CharField(blank=True, help_text='Police OB Number', max_length=50)),
                ('police_station', models.CharField(blank=True, max_length=100)),
                ('investigating_officer', models.CharField(blank=True, max_length=100)),
                ('date_of_arrival', models.DateTimeField(auto_now_add=True)),
                ('qr_code_image', models.ImageField(blank=True, upload_to='qr_codes/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('POLICE', 'Police Officer'), ('PATHOLOGIST', 'Pathologist')], default='POLICE', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('chain_of_custody', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='api.autopsycase')),
            ],
        ),
        migrations.CreateModel(
            name='AutopsyReport',
            fields=[
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='report', serialize=False, to='api.autopsycase')),
                ('exam_date', models.DateTimeField(auto_now_add=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('rigor_mortis', models.CharField(blank=True, max_length=100)),
                ('livor_mortis', models.CharField(blank=True, max_length=100)),
                ('clothing_description', models.TextField(blank=True)),
                ('scars_tattoos', models.TextField(blank=True)),
                ('external_injuries', models.TextField(blank=True)),
                ('heart_weight', models.FloatField(blank=True, help_text='Grams', null=True)),
                ('lung_right_weight', models.FloatField(blank=True, help_text='Grams', null=True)),
                ('lung_left_weight', models.FloatField(blank=True, help_text='Grams', null=True)),
                ('liver_weight', models.FloatField(blank=True, help_text='Grams', null=True)),
                ('spleen_weight', models.FloatField(blank=True, help_text='Grams', null=True)),
                ('kidney_right_weight', models.FloatField(blank=True, help_text='Grams', null=True)),
                ('kidney_left_weight', models.FloatField(blank=True, help_text='Grams', null=True)),
                ('brain_weight', models.FloatField(blank=True, help_text='Grams', null=True)),
                ('heart_findings', models.TextField(blank=True)),
                ('lung_findings', models.TextField(blank=True)),
                ('liver_findings', models.TextField(blank=True)),
                ('stomach_contents', models.TextField(blank=True)),
                ('neck_findings', models.TextField(blank=True)),
                ('specimens_collected', models.TextField(blank=True, help_text='e.g. Heart Blood, Femoral Blood, Vitreous, Urine, Liver')),
                ('toxicology_results', models.TextField(blank=True, help_text='Detailed drug levels (e.g. Ketamine 3240 ng/mL)')),
                ('lab_name', models.CharField(blank=True, help_text='Lab performing the analysis', max_length=100)),
                ('cause_of_death', models.TextField()),
                ('manner_of_death', models.CharField(choices=[('NATURAL', 'Natural'), ('ACCIDENT', 'Accident'), ('SUICIDE', 'Suicide'), ('HOMICIDE', 'Homicide'), ('UNDETERMINED', 'Undetermined')], default='UNDETERMINED', max_length=20)),
                ('final_summary', models.TextField(blank=True)),
                ('pathologist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
