# Generated by Django 6.0.1 on 2026-01-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autopsyreport',
            name='external_injuries',
        ),
        migrations.AddField(
            model_name='autopsycase',
            name='external_injuries',
            field=models.TextField(blank=True),
        ),
    ]
