# Generated by Django 6.0.1 on 2026-01-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_autopsyreport_external_injuries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopsycase',
            name='body_map_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autopsycase',
            name='external_injuries',
            field=models.TextField(blank=True, null=True),
        ),
    ]
