# Generated by Django 6.0.1 on 2026-01-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_autopsycase_body_map_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopsycase',
            name='circumstances_of_death',
            field=models.TextField(blank=True, help_text='Police report summary, scene investigation notes'),
        ),
        migrations.AddField(
            model_name='autopsycase',
            name='identification_method',
            field=models.CharField(choices=[('VISUAL', 'Visual Identification'), ('ID_CARD', 'ID Document found on body'), ('FINGERPRINT', 'Fingerprint Analysis'), ('DNA', 'DNA Profiling'), ('DENTAL', 'Dental Records (Odontology)'), ('UNKNOWN', 'Unidentified')], default='VISUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='autopsycase',
            name='identification_notes',
            field=models.TextField(blank=True, help_text='Details of who identified the body and how'),
        ),
        migrations.AddField(
            model_name='autopsycase',
            name='medical_history',
            field=models.TextField(blank=True, help_text='Relevant pre-existing conditions (Diabetes, Hypertension, etc.)'),
        ),
        migrations.AddField(
            model_name='autopsycase',
            name='place_of_death',
            field=models.CharField(blank=True, help_text='Location where death occurred', max_length=200),
        ),
        migrations.AddField(
            model_name='autopsycase',
            name='race',
            field=models.CharField(blank=True, help_text='e.g. African, Caucasian, Asian, Mixed', max_length=50),
        ),
        migrations.AddField(
            model_name='autopsycase',
            name='time_of_death',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autopsyreport',
            name='body_habitus',
            field=models.CharField(choices=[('EMACIATED', 'Emaciated/Cachectic'), ('THIN', 'Thin'), ('NORM', 'Normal/Athletic'), ('OBESE', 'Obese'), ('MORBID', 'Morbidly Obese')], default='NORM', max_length=20),
        ),
        migrations.AddField(
            model_name='autopsyreport',
            name='decomposition_changes',
            field=models.TextField(blank=True, help_text='Bloating, skin slippage, insect activity'),
        ),
        migrations.AddField(
            model_name='autopsyreport',
            name='dentition_status',
            field=models.CharField(blank=True, help_text='Natural, Dentures, Edentulous', max_length=100),
        ),
        migrations.AddField(
            model_name='autopsyreport',
            name='endocrine_findings',
            field=models.TextField(blank=True, help_text='Thyroid, Adrenals, Pituitary'),
        ),
        migrations.AddField(
            model_name='autopsyreport',
            name='evidence_disposition',
            field=models.TextField(blank=True, help_text='List of items collected and who received them'),
        ),
        migrations.AddField(
            model_name='autopsyreport',
            name='evisceration_technique',
            field=models.TextField(blank=True, default='Standard Y-incision and Rokitansky technique.'),
        ),
        migrations.AddField(
            model_name='autopsyreport',
            name='eye_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='autopsyreport',
            name='fluid_findings',
            field=models.TextField(blank=True, help_text='Pleural effusion, ascites, hemothorax'),
        ),
        migrations.AddField(
            model_name='autopsyreport',
            name='genitalia_findings',
            field=models.TextField(blank=True, help_text='Prostate/Testes or Uterus/Ovaries'),
        ),
        migrations.AddField(
            model_name='autopsyreport',
            name='hair_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='autopsyreport',
            name='histology_results',
            field=models.TextField(blank=True, help_text='Microscopic findings'),
        ),
        migrations.AddField(
            model_name='autopsyreport',
            name='medical_interventions',
            field=models.TextField(blank=True, help_text='CPR marks, IV lines, intubation'),
        ),
        migrations.AddField(
            model_name='autopsyreport',
            name='microbiology_results',
            field=models.TextField(blank=True, help_text='Cultures (Blood, CSF)'),
        ),
        migrations.AddField(
            model_name='autopsyreport',
            name='musculoskeletal_findings',
            field=models.TextField(blank=True, help_text='Rib fractures, muscle development'),
        ),
        migrations.AddField(
            model_name='autopsyreport',
            name='nutrition_notes',
            field=models.TextField(blank=True, help_text='Hydration, muscle wasting, etc.'),
        ),
        migrations.AddField(
            model_name='autopsyreport',
            name='personal_effects',
            field=models.TextField(blank=True, help_text='Jewelry, cash, items found on body'),
        ),
        migrations.AddField(
            model_name='autopsyreport',
            name='postmortem_imaging',
            field=models.TextField(blank=True, help_text='X-Ray / CT Scan findings'),
        ),
        migrations.AlterField(
            model_name='autopsyreport',
            name='lab_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='autopsyreport',
            name='specimens_collected',
            field=models.TextField(blank=True, help_text='e.g. Heart Blood, Femoral Blood, Vitreous'),
        ),
        migrations.AlterField(
            model_name='autopsyreport',
            name='toxicology_results',
            field=models.TextField(blank=True, help_text='Detailed drug levels'),
        ),
    ]
