# Generated by Django 6.0.1 on 2026-01-30 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_autopsycase_circumstances_of_death_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopsyreport',
            name='organ_retention',
            field=models.TextField(blank=True, default='All organs returned to body.', help_text='Were any organs retained for teaching/further study?'),
        ),
        migrations.AddField(
            model_name='autopsyreport',
            name='pathologic_diagnoses',
            field=models.TextField(blank=True, help_text='List of findings (FAD). One per line.'),
        ),
        migrations.CreateModel(
            name='HistologyCassette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cassette_id', models.CharField(help_text='e.g. A1, B2', max_length=10)),
                ('tissue_type', models.CharField(help_text='e.g. Left Ventricle, Liver', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Microscopic findings for this specific slide')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cassettes', to='api.autopsyreport')),
            ],
        ),
    ]
