# Generated by Django 6.0.1 on 2026-01-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_autopsyreport_organ_retention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopsyreport',
            name='cause_of_death',
            field=models.TextField(blank=True),
        ),
    ]
