# Generated by Django 6.0.1 on 2026-02-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_allow_blank_cause_of_death'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
