# Generated by Django 6.0.1 on 2026-03-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_reopened_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopsycase',
            name='date_of_arrival',
            field=models.DateTimeField(blank=True, help_text='When the body arrived at the morgue', null=True),
        ),
    ]
