# Generated by Django 6.0.1 on 2026-03-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_autopsycase_date_of_arrival'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ministry of Health - Kenya', max_length=200)),
                ('department', models.CharField(default='Department of Forensic Pathology', max_length=200)),
                ('address', models.TextField(blank=True, help_text='Official address')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True, help_text='URL to organization logo')),
                ('report_footer', models.TextField(default='This is an official government document. Unauthorized reproduction is prohibited.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
    ]
