# Generated by Django 6.0.1 on 2026-03-14 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='autopsycase',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='api.organization'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Employee/Staff ID', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.organization'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, help_text='Organization logo', upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('MINISTRY', 'Ministry of Health'), ('HOSPITAL', 'Government Hospital'), ('PRIVATE', 'Private Institution')], default='MINISTRY', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_orgs', to='api.organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(default='#2563eb', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='organization',
            name='secondary_color',
            field=models.CharField(default='#1e40af', help_text='Hex color code', max_length=7),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('MINISTRY_ADMIN', 'Ministry Administrator'), ('MINISTRY_SUPERVISOR', 'Ministry Supervisor'), ('HOSPITAL_ADMIN', 'Hospital Administrator'), ('PATHOLOGIST', 'Pathologist'), ('POLICE', 'Police Officer'), ('LAB_TECH', 'Laboratory Technician')], default='POLICE', max_length=20),
        ),
    ]
