# Generated by Django 6.0.1 on 2026-03-14 07:12

from django.db import migrations


def create_default_organizations(apps, schema_editor):
    Organization = apps.get_model('api', 'Organization')

    # Create Ministry of Health organization
    ministry_org = Organization.objects.create(
        name="Ministry of Health - Republic of Kenya",
        org_type="MINISTRY",
        department="Department of Forensic Pathology",
        address="Afya House, Cathedral Road, Nairobi, Kenya",
        phone="+254 20 2717077",
        email="info@health.go.ke",
        website="https://www.health.go.ke",
        primary_color="#2563eb",
        secondary_color="#1e40af",
        report_footer="This is an official government document. Unauthorized reproduction is prohibited."
    )

    # Create a default hospital organization
    hospital_org = Organization.objects.create(
        name="Kenyatta National Hospital",
        org_type="HOSPITAL",
        department="Forensic Pathology Unit",
        address="Hospital Road, Nairobi, Kenya",
        phone="+254 20 2726300",
        email="info@knh.or.ke",
        primary_color="#dc2626",
        secondary_color="#b91c1c",
        parent_org=ministry_org,
        report_footer="This is an official government hospital document."
    )


def assign_default_organizations(apps, schema_editor):
    Organization = apps.get_model('api', 'Organization')
    CustomUser = apps.get_model('api', 'CustomUser')
    AutopsyCase = apps.get_model('api', 'AutopsyCase')

    # Get the default hospital organization
    try:
        default_org = Organization.objects.filter(org_type='HOSPITAL').first()
        if not default_org:
            # Fallback to ministry if no hospital exists
            default_org = Organization.objects.filter(org_type='MINISTRY').first()

        if default_org:
            # Assign organization to existing users
            CustomUser.objects.filter(organization__isnull=True).update(organization=default_org)

            # Assign organization to existing cases
            AutopsyCase.objects.filter(organization__isnull=True).update(organization=default_org)
    except Exception as e:
        # If something goes wrong, we'll handle it manually
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_extend_organization_model'),
    ]

    operations = [
        migrations.RunPython(create_default_organizations, migrations.RunPython.noop),
        migrations.RunPython(assign_default_organizations, migrations.RunPython.noop),
    ]
