from django.http import HttpResponse
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from rest_framework.decorators import action
from rest_framework.response import Response
from django.utils import timezone
from rest_framework import viewsets, permissions
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.authtoken.models import Token
from rest_framework.response import Response
from .models import CustomUser, AutopsyCase, Evidence, AutopsyReport
from .serializers import UserSerializer, AutopsyCaseSerializer, EvidenceSerializer, ReportSerializer

# 1. User ViewSet
class UserViewSet(viewsets.ModelViewSet):
    queryset = CustomUser.objects.all()
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated] # Only logged-in users

# 2. Case ViewSet
class AutopsyCaseViewSet(viewsets.ModelViewSet):
    queryset = AutopsyCase.objects.all().order_by('-date_of_arrival')
    serializer_class = AutopsyCaseSerializer
    @action(detail=True, methods=['get'])
    def download_pdf(self, request, pk=None):
        autopsy_case = self.get_object()
        
        # Create the HttpResponse object with the appropriate PDF headers.
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="Report_{autopsy_case.case_id}.pdf"'

        # Create the PDF object, using the response object as its "file."
        p = canvas.Canvas(response, pagesize=A4)
        width, height = A4

        # --- HEADER ---
        p.setFont("Helvetica-Bold", 16)
        p.drawString(50, height - 50, "MINISTRY OF HEALTH - KENYA")
        p.setFont("Helvetica", 12)
        p.drawString(50, height - 70, "Department of Forensic Pathology")
        
        # Draw a line
        p.line(50, height - 80, width - 50, height - 80)

        # --- CASE INFO ---
        y = height - 120
        p.setFont("Helvetica-Bold", 12)
        p.drawString(50, y, f"CASE REPORT: {autopsy_case.case_id}")
        
        p.setFont("Helvetica", 11)
        y -= 25
        p.drawString(50, y, f"Deceased: {autopsy_case.deceased_name}")
        p.drawString(300, y, f"OB Number: {autopsy_case.ob_number}")
        
        y -= 20
        p.drawString(50, y, f"Age/Gender: {autopsy_case.age} / {autopsy_case.gender}")
        p.drawString(300, y, f"Date: {autopsy_case.date_of_arrival.strftime('%Y-%m-%d')}")

        # --- THE FINDINGS (Check if report exists) ---
        # --- THE FINDINGS (Safe Check) ---
        y -= 40
        p.line(50, y, width - 50, y)
        y -= 30
        
        # Check if the attribute 'report' exists on the case object
        if hasattr(autopsy_case, 'report'):
            report = autopsy_case.report
            
            p.setFont("Helvetica-Bold", 12)
            p.drawString(50, y, "CAUSE OF DEATH:")
            p.setFont("Helvetica", 11)
            y -= 20
            p.drawString(50, y, f"{report.cause_of_death}")
            
            y -= 40
            p.setFont("Helvetica-Bold", 12)
            p.drawString(50, y, "MANNER OF DEATH:")
            p.setFont("Helvetica", 11)
            p.drawString(200, y, f"{report.manner_of_death}")

            y -= 40
            p.setFont("Helvetica-Bold", 12)
            p.drawString(50, y, "EXAMINATION NOTES:")
            y -= 20
            
            # Simple text wrapping for long notes
            text = p.beginText(50, y)
            text.setFont("Helvetica", 10)
            text.textLines(report.details)
            p.drawText(text)
        else:
            # If no report exists yet
            p.setFont("Helvetica-Oblique", 12)
            p.setFillColor(colors.red)
            p.drawString(50, y, "PENDING PATHOLOGIST REPORT")

        # --- FOOTER ---
        p.setFont("Helvetica", 9)
        p.setFillColor(colors.black)
        p.drawString(50, 50, f"Generated by DACMS on {timezone.now().strftime('%Y-%m-%d %H:%M')}")
        p.drawString(50, 35, "This is a computer-generated document.")

        # Close the PDF object cleanly, and we're done.
        p.showPage()
        p.save()
        return response

# 3. Evidence ViewSet
class EvidenceViewSet(viewsets.ModelViewSet):
    queryset = Evidence.objects.all()
    serializer_class = EvidenceSerializer

# 4. Report ViewSet
class ReportViewSet(viewsets.ModelViewSet):
    queryset = AutopsyReport.objects.all()
    serializer_class = ReportSerializer

# Custom Login View that returns the Role
class CustomLoginView(ObtainAuthToken):
    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data, context={'request': request})
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        token, created = Token.objects.get_or_create(user=user)
        return Response({
            'token': token.key,
            'user_id': user.pk,
            'username': user.username,
            'role': user.role  # <--- This is the golden ticket
        })
    

class RegisterUserView(APIView):
    def post(self, request):
        # 1. Security Check: Only Admins can create users
        if not request.user.is_superuser and request.user.role != 'ADMIN':
            return Response({'error': 'Unauthorized'}, status=status.HTTP_403_FORBIDDEN)

        # 2. Get Data
        username = request.data.get('username')
        password = request.data.get('password')
        role = request.data.get('role')

        # 3. Validation
        if not username or not password or not role:
            return Response({'error': 'All fields are required'}, status=status.HTTP_400_BAD_REQUEST)

        if CustomUser.objects.filter(username=username).exists():
            return Response({'error': 'Username already exists'}, status=status.HTTP_400_BAD_REQUEST)

        # 4. Create User
        try:
            user = CustomUser.objects.create_user(username=username, password=password, role=role)
            return Response({'message': f'User {username} created successfully!'}, status=status.HTTP_201_CREATED)
        except Exception as e:
            return Response({'error': str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)